import type { Metadata } from "next";

import "./styles/global.scss";

import '@fontsource/rubik';

import { ThemeProvider } from "./context/ThemeContext";

import 'react-tooltip/dist/react-tooltip.css'
import Footer from "./components/footer/footer";



export const metadata: Metadata = {
  title: "Mesh Balsalfa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body>
        <ThemeProvider>

          <div className="main">{children}</div>
          
          
          <Footer />
        </ThemeProvider>


      </body>
    </html>
  );
}
